---
bots:
  -
    client_access_token: 48f55cfe1f8f4d69b798864fbea01b60
    name: Homeassistant
  -
    client_access_token: 1a2f8bac724f45aa828f82e38d3f3a87
    name: Tasker
join:
  api_key: ae854ef404d341dc82fca9514642fc26
  devices:
    -
      device_id: 5b96a4cfe0ef47da8b771e00be365e61
      name: phone
